### ISSUE TITLE
As a disaster Coordinator I can email all checked-in relief workers

### ISSUE THREAD

**Issue by BillWagner** [HTBox/crisischeckin#10]
Disaster Coordinators need to email all volunteers that are checked in. That's how coordinators get assignments to volunteers.

**Comment by tditiecher** [comment]
Is **disaster** coordinator equal to **humanitarian** coordinator (as mentioned on https://github.com/HTBox/crisischeckin/wiki/2.0-Domain-Model) ?

Would it be sufficient to add an extra checkbox **only send to checked-in volunteers** to the existing 'Send Message to Volunteers' form to complete this user story and close this issue?

**Comment by BillWagner** [comment]
@tditiecher That would be the best way to handle this request and close this task.
