### ISSUE TITLE
As a disaster coordinator, I can filter the volunteer list by cluster

### ISSUE THREAD

**Issue by BillWagner** [HTBox/crisischeckin#12]
Some coordinators only work in one cluster

**Comment by asherw** [comment]
Is this ticket to implement the roles and security structure listed here? (https://github.com/HTBox/crisischeckin/wiki/2.0-Domain-Model)

**Comment by BillWagner** [comment]
@asherw Yes, that's correct. The Cluster coordinator role is mostly in place today, but is not quite integrated in terms of the features that the cluster coordinate can use. 

The Humanitarian Coordinator role is not implemented at all. Do you want to take this on?

**Comment by kinetiq** [comment]
I wouldn't mind helping with this one, but reading over the ticket, the requirements seem like they might need to be clarified more.

Specifically: what, if anything, needs to happen with Cluster Coordinator before this ticket can be attacked?

**Comment by BillWagner** [comment]
@kinetiq I believe that since Feb we've got the cluster coordinator in place. PR #263 should have finished that work.

What should happen here now is that when a user is in the cluster coordinator role, that person should be managing a single cluster. They should effectively have the same rights as the administrator, but the list of users they manage is filtered to those in the cluster they manager. (e.g. Medical only sees Medical volunteers, Food sees Food, etc.) 

In addition, any cluster coordinate should be able to communicate with other cluster coordinators directly.

Does that make sense?

**Comment by kinetiq** [comment]
It seems to make sense, from my perspective of knowing very little about the project. I will take a closer look at the code and the database to get an idea of what's involved.

**Comment by kinetiq** [comment]
Quick update: I haven't forgotten about this, I just got busy this week.

**Comment by BillWagner** [comment]
This might be closed as not needed, after implementing the cluster coordinator role.
