### ISSUE TITLE
Our EF Migration strategy needs help

### ISSUE THREAD

**Issue by BillWagner** [HTBox/crisischeckin#126]
We started the project thinking that EF automatic migrations and CodeFirst would be the way to go. Well, those don't play well with SQL Azure.  Later in the process, we moved form an automatic migration model to manual migrations.

It hurts us.  Some new contributors are reporting problems getting the system installed. We also are more concerned with making model changes than we should be at this point in time. 

If anyone has mad EF skills and can help fix this, and update our docs to provide a better experience, that would be fantastic.

**Comment by asherw** [comment]
Hi Bill,

At my place of work, we use [dbup](http://dbup.github.io/) in many projects, with great success.

With asp.net projects on the local dev machine, when the developer starts the website, we do a call to the dbup code in the Application_Start() to perform the upgrade process.
This way when devs are doing regular pulls, their database is kept up to date with the recent changes.  
All scripts executed are stored in a database table called SchemaVersions.

When deploying to QA and production, we have one of the machines perform the upgrade via a console application (stops multiple executions).

Script execute order is simply alpha numeric order.

A developer making a database table change would simply create a new dbup script, add it as an embedded resource, and check that in along with the other required changes, eg model changes, etc.


I am more than happy to implement all the required code in a fork and do a pull request if you like the sound of it.

I have yet to use dbup against azure, but dbup supports it and I've just opened an azure account.


Regards,
Asher

**Comment by BillWagner** [comment]
@asherw I'd like to see how this might work. I'm tagging @tonysurma on this. He did do quite a bit of work getting us back to where our migrations work well. He has very deep azure knowledge and can help make sure this works both locally (for devs) and in Azure. 

How long would the fork and pull take? I don't want to have you make a large commitment until we are sure it's the right path.

**Comment by asherw** [comment]
Ah understandably.

Bare with me while I'll get up to speed, I'll probably ask lots of stupid questions.

The DbMigration code is the latest work to have automatic database changes deployed?
Is it functioning well at the moment?  or is that the item that isn't working with azure?

**Comment by tonysurma** [comment]
@asherw thanks for jumping in.  As with other issues this should have been closed after Codemash as it was resolved there.  I basically took migrations in Entity Framework which we had but had gotten jumbled with past checkins and cleaned them up and added  a little infrastructure so they worked properly in our multiple environments and in a way not unlike dbup (which I agree is quite nice) that you mentioned.  I have a write up on it I will be posting soon.
