### ISSUE TITLE
Feature test suites please

### ISSUE THREAD

**Issue by BillWagner** [HTBox/crisischeckin#129]
I'd really like to see someone take on the task of writing some Fitness (Or whatever tool you prefer) end to end feature tests.

**Comment by BanksySan** [comment]
As this seems to be a jump in issue, I'll start kicking something simple off.  Just vanilla C#.

**Big Question** do you want controller level testing of front end level testing?  Seeing as you have a cross platform site, I'd quite like to see how Selenium can cope with that, would be quite a challenge.  Let me know any concerns\questions\comments you might have.

**Comment by BillWagner** [comment]
@BanksySan I'd like to see how Selenium handles this. There is risk, so I'd like to see that start on a branch, until we've validated that it does work correctly for us on all platforms. After that is validated, we can merge the branch.

**Comment by BanksySan** [comment]
@BillWagner Would you be able to give me a couple of typical user journeys to implement?

**Comment by BillWagner** [comment]
I will bump this to @tonysurma He has more experience here in the most common scenarios for delays and rescheduling.

**Comment by BillWagner** [comment]
Closing. We have the framework, but still have some technical debt on different scenarios. We'll add new issues for each scenario.

**Comment by BanksySan** [comment]
I'll get back on this (I've added allot more) but have been pretty swamped over the last few weeks.
