### ISSUE TITLE
Error when trying to change contact info logged in as admin

### ISSUE THREAD

**Issue by nterry** [HTBox/crisischeckin#134]
It appears that Administrator isn't a Volunteer account and thus cant Commit to Disasters. Admin also appears to not have user details on his model ans thus, the change contact info link at the top results in an exception. 

Recommend hiding button or catching condition and returning a graceful message.

**Comment by tditiecher** [comment]
@BillWagner The symptom described by the issue title is solved (the admin has no option to change the contact info anymore).

**Comment by BillWagner** [comment]
Thank you. Closed.
