### ISSUE TITLE
Column Name Disaster name is not readable

### ISSUE THREAD

**Issue by drosskopf** [HTBox/crisischeckin#16]
On the Crisis Check in page, under My comments, it shows hard to read 'a' and 's'.  Suggest font change.  
![bug1](https://f.cloud.github.com/assets/5590134/1250271/c134d0d6-2af3-11e3-96a6-3fda30dcafea.JPG)

**Comment by tditiecher** [comment]
@BillWagner We are using the default Bootstrap font ('Helvetica Neue', Helvetica, Arial, sans-serif). What do you think of the suggested font change?

**Comment by BillWagner** [comment]
I'd prefer just leaving this alone at this time. No one else has had any readability concerns, IT's been 18 months, so I'm going to close it. If others have issues, we can revisit.
