### ISSUE TITLE
Move 'Add new disaster' button to the top of the page

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#171]
Currently, there isn't a way to minimize the list of Disasters, which creates an indefinitely long list of disasters to scroll through to get to the "Add a New Disaster" button.

**Comment by Pilchie** [comment]
This looks like it's fixed.  Should the issue be closed?

**Comment by BillWagner** [comment]
Thanks @Pilchie   Fixed in July 2014.
