### ISSUE TITLE
Jquery/css included twice on volunteer home page page

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#173]
*Bootstrap min and the not min file are both included on this page
*Jquery 1.9.1 is included twice (one in /Scripts/, one in/scripts/
*Some of this is included in the head, and some in the body - there isn't really a need for this

**Comment by gustavorhm** [comment]
Create pull request #254.

**Comment by BillWagner** [comment]
Fixed in pull request #254
