### ISSUE TITLE
Clear text password sending to the server

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#181]
The site isn't under SSL and I can see my password in clear text over the wire.

http://crisischeckin.azurewebsites.net/Account/Login

If the username/password combo is used on another site (which it probably is because people do that...), then you want to at least secure the user/password send on login & also register user pages.

**Comment by tditiecher** [comment]
@BillWagner Is it possible to deploy the website under SLL so that this issue can be closed?

**Comment by tonysurma** [comment]
Thanks.  I will update config to 301 redirect non-ssl in release as all sites on azure can be accessed via https at the same url by default.  Also the url has been updated (per readme) so issue should use https://crisischeckin-d.azurewebsites.net/Account/Login
