### ISSUE TITLE
Register Page - Label has cursor:pointe

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#186]
There is a style on the form labels (see attachment) to make the mouse a pointer. Since this isn't a clickable element, seems like a bug!

**Comment by asherw** [comment]
[Appears to be fixed now](http://i.imgur.com/Eqc0KXf.png)

**Comment by BillWagner** [comment]
@asherw Thank you. That was fixed at CodeMash. Closing.
