### ISSUE TITLE
Request: There is no method of password recovery in the website

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#187]
This hit us in the test lab pretty hard, as there were a couple times where the admin user's password was changed, and seemed to break completely. Having a self-serve way of resetting the password would be good for us, and for end users.

**Comment by tditiecher** [comment]
@BillWagner I will implement the Password reset functionality as described on the [Websecurity.GeneratePasswordResetToken help page](https://msdn.microsoft.com/en-us/library/webmatrix.webdata.websecurity.generatepasswordresettoken(v=vs.111).aspx)

About your comment on this issue about having multiple admin accounts, the admin password cannot be changed anymore so there seems to be no relation anymore between the password reset and multiple admin accounts. I think this should be a separate issue if multiple admins are still needed but I'm not sure about the exact requirements (so maybe I should not be the one to create that new issue).

**Comment by BillWagner** [comment]
The main issue has been handled in PR #271 I've opened a new issue to address the multiple admin accounts.
