### ISSUE TITLE
Removing Coordinator from Cluster Assignment

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#195]
In ADMIN mode - Pick a Disaster and click on the Cluster Coordinators.

Click on the "X" . Navigated to confirmation page.

Click "YES" button..Will be navigated back to the "Cluster Coordinators" page

Click "BACK" button...and Again click "YES" button.. instead of navigating back to the "Cluster Coordinators" page.. will be navigated to the "Volunteer Home" page!!!

**Comment by lunateth** [comment]
Looking into this

**Comment by tditiecher** [comment]
@lunateth Are you still working on this issue?

**Comment by tditiecher** [comment]
As the user 'lunateth' is deleted from github, I'll have a look into this issue.
