### ISSUE TITLE
Register password restrictions

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#196]
There were lots of bugs opened at StarEast about password creation int he registration process. All are pasted below:

Enter mismatching password/confirm password and no immediate feedback is provided - Expected, after encountering Issue 33 (feedback that I did not expect) that I would have received immediate feedback on the mismatched password

No info on password requirements until you have a validation issue (must be > 6 chars, etc)

password and confirm password should confirmed at input time instead of submission time - The proper behavior should be when input password and confirm password. It should confirm at input time instead submission time.

**Comment by tditiecher** [comment]
I'll implement this by sending ajax requests to the server and requesting the [PasswordComplexity](https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/crisicheckinweb/Infrastructure/PasswordComplexity.cs) class.

**Comment by tditiecher** [comment]
@BillWagner I assume your comment on this issue was meant for another issue as it seems unrelated?

**Comment by tditiecher** [comment]
@BillWagner I implemented this and will post a pull request as soon as #271 (implementation of password reset functionality) is merged. My current solution builds on top of that code.

**Comment by BillWagner** [comment]
@tditiecher Yes, my comment was for issue #187 and related to the multiple admin accounts.

What caused all the confusion: one of the test professionals at a hackathon changed the admin password, and didn't tell anyone what the new PW was before leaving. We were pretty well stuck. It did point out a big hole though,.
