### ISSUE TITLE
After logout, a user can press "back" and still see volunteer info.

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#199]
After clicking Logout from the Volunteer Home page, I pressed Backspace and returned successfully to the Volunteer page.

**Comment by asherw** [comment]
I've a fix for this.

I've got a pending pull request.  Do I make a branch, apply fix there, and will that let me submit a 2nd pull request?

**Comment by BillWagner** [comment]
@asherw I'm around today.  I can either approve the existing pull request, or let you update it with this fix as well (as @tonysurma said).  

Let me know which works better for you, and I'll handle it on this end.

**Comment by asherw** [comment]
ah, gotchya.
Ok I've committed the change.  Pull request is good to go.  Thanks!

**Comment by BillWagner** [comment]
Fixed in PR #242

**Comment by BillWagner** [comment]
Fixed in PR #242
