### ISSUE TITLE
Bootstrap glyphicons not working on AssignCoordinator partial view

### ISSUE THREAD

**Issue by brunck** [HTBox/crisischeckin#206]
The view is trying to use glyphicons via the classes "close" and "icon-remove" but nothing is visible, and Chrome inspection shows that there is a link element but it is of 0px height and width. Confirmed this problem on this page with both FF and Chrome.

I tried this out by using these classes on other elements; notably the Assign button at the bottom of the page, which showed up but very faintly. Using them on <a> tags like we have in this view don't work at all. I tried this on other views as well, and tried using bootsrap.css as well as bootstrap.min.css with the same results. Both files have the same paths for the glyphicons-halflings files (../fonts).

We do seem to have the glyphicon font files in the ~/Content/fonts folder, which is what the paths to those files are set to in the bootstrap.css file (see the @font-face section), but they aren't working. Not sure if these are damaged files as was a problem with customized Boostrap 3 (as opposed to the non-customized one, which worked), because they supposedly fixed that in a previous release. We currently have 3.1.1 (as of 7/21/14) so presumably that isn't the problem, although I didn't try to replace those files. Shawn seemed to be on top of getting Bootstrap 3 in place, but it might be worth trying to replace those files locally in ~/Content/fonts just to see what happens.

**Comment by BillWagner** [comment]
Fixed in Pull Request #229
