### ISSUE TITLE
Is a separate Username really necessary?

### ISSUE THREAD

**Issue by Redth** [HTBox/crisischeckin#210]
Creating an account requires that you specify a username as well as an email.  This makes remembering your information a bit more difficult, and also requires more entry for the registration process (which is a bigger deal on mobile).  Is it really necessary to have a Username?  Can we just make the username be the email?  Or at the very least, can we add some logic in the login api to check both username/password and email/password combos to login?

**Comment by tditiecher** [comment]
@BillWagner  I implemented login and password reset functionality by using both username and email and will post a pull request as soon as #271 (implementation of password reset functionality) is merged and I posted another PR to fix #196 (immediate password validity feedback). My current solution builds on top of that code.
