### ISSUE TITLE
Administrator Loggin does not have enough information

### ISSUE THREAD

**Issue by SuppaDev** [HTBox/crisischeckin#219]
The current administrator login that is preconfigured with the project does not contain enough filled out information to send emails. currently results in exceptions thrown with header containing invalid <>

**Comment by tditiecher** [comment]
@BillWagner This issue probably can be closed.
* The problem in the first comment cannot be reproduced anymore as the sender is now [set in code](https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/Services/SmtpMessageSender.cs#L27).
* This issue in the second comment is a duplicate of #245 (SmtpMessageSender is not using injected SmtpSettings).

**Comment by BillWagner** [comment]
Thanks for the investigation. Closed based on verifying.
