### ISSUE TITLE
Cannot change a disasters 'IsActive' flag

### ISSUE THREAD

**Issue by OnTheFenceDevelopment** [HTBox/crisischeckin#224]
I'm (potentially) a new contributor to the project and have recently been feeling my way around the system.

When I click the 'Edit' link associated with a Disaster I am taken to the Create/Edit Disaster page. Unchecking the 'Is Currently Active' checkbox and clicking the 'Create' button the result is an error stating that the Disaster name already exists.

![crisis_checkin_edit_disaster](https://cloud.githubusercontent.com/assets/1759701/5570651/057f768a-8f7d-11e4-8acd-53746e0d95fc.png)

I've had a quick look through the code and am happy to 'get my feet wet' addressing this issue :-)

**Comment by OnTheFenceDevelopment** [comment]
Ok, there are two commits above but only one (the later one) is valid. The changes are the same but I managed to mess up my branching so had to back it all out.

**Comment by TravCav** [comment]
I'm unable to reproduce this. Has it been fixed?

**Comment by OnTheFenceDevelopment** [comment]
I believe my previous commit fixed this - merged now so closing issue
