### ISSUE TITLE
Unable to run Android application

### ISSUE THREAD

**Issue by OnTheFenceDevelopment** [HTBox/crisischeckin#227]
I've checked out the Mobile branch and it builds successfully but when I try to run it I get a Null Reference Exception within <code>App.GetMainPage()</code>.

I have started an instance of CrisisCheckinWeb which runs fine but with I try to navigate to the URL specified in the ClientModel definition I get a 404 error.

I've trawled the documentation and can't find any special configuration instructions for the mobile project. Can someone enlighten me or point me in the right direction here - I'd be happy to produce the required documentation once I have my system running.

**Comment by brunck** [comment]
The Mobile branch should have been merged into Master some time ago. @BillWagner do you agree we should delete the Mobile branch on the origin?

**Comment by brunck** [comment]
@OnTheFenceDevelopment in the meantime I definitely suggest using master for a basis of building the mobile projects. I checked and do see the mobile branch's commits in master (head from Aug 10th) I added more mobile changes to master after that time.

**Comment by OnTheFenceDevelopment** [comment]
I opted for the Mobile branch as the Mobile.sln file had been removed from master previously so I assumed it was to segregate the development.
I'll take another run at it and let you know how I get on

**Comment by BillWagner** [comment]
@OnTheFenceDevelopment We had temporarily removed the mobile.sln file from master because of the automatic build / deployment scripts. Those broke when the build included the mobile projects because the Azure deployment infrastructure does not have the necessary Xamarin libraries. (That makes sense, since we're not running the xamarin projects in the cloud. We added the web and mobile sln's and reconfigured the deployment scripts to run the web only solution. I hope that helps.

**Comment by brunck** [comment]
Ok so I've been working on a separate branch which has been kept up to date with master. Once I get that pushed up, we can work on that (which does have a .sln file so that I could develop in Xamarin Studio), if we want to keep that separate from master.

**Comment by OnTheFenceDevelopment** [comment]
I've been a bit swamped here since raising this issue and not really had some to revisit. Happy to take another run at it in the next week or so.
