### ISSUE TITLE
Email Sending needs full testing/fixing in dev using test tool

### ISSUE THREAD

**Issue by tonysurma** [HTBox/crisischeckin#235]
Email sending has been broadly implemented using app settings for servers, usernames and passwords.

Before we connect production live we need to test the functionality with a 'test' smtp server in a local respository.

Whoever picks that up should use something like http://papercut.codeplex.com/ which is a local listening smtp server which stores 'received' emails locally so that no emails are actually sent but you still can review them to see if they are working.

Working on this will allow us to then turn on 'really' sending emails from production and something in between in development.  This will then address issue #191

**Comment by TravCav** [comment]
This appeals to my love of unit testing. I'm gonna look into this unless anyone has already started on it.

**Comment by TravCav** [comment]
Created a pull request that should help with this.  Probably room for improvement. open to suggestions.

**Comment by tditiecher** [comment]
@BillWagner What has to be done to close this issue? With the solution of @TravCav to store the mails in the specified pickup directory in debug mode you can test the email functionality locally.

**Comment by BillWagner** [comment]
Addin @tonysurma.  We want to be able to run testing scenarios on the staging site. However, the staging site should not send live email, because the admin accounts are published for the volunteer orgs that help us run live testing. I believe Tony had a proposed solution here.

**Comment by BillWagner** [comment]
This should now be closed as the requirements changed for testing and 2 factor auth (see Issue #286 and #301)
