### ISSUE TITLE
Volunteer Home list with cluster commitments doesn't show cluster coordinators.

### ISSUE THREAD

**Issue by tditiecher** [HTBox/crisischeckin#248]
When creating the default VolunteerVieModel fetching the cluster coordinators always uses cluster id 1 instead of the cluster id the current user belongs to.
https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/crisicheckinweb/Controllers/HomeController.cs#L91
The result is that if a user doesn't belong to cluster 1 no cluster coordinator(s) will be shown in the list.

(a pull request to fix this is on its way)

**Comment by BillWagner** [comment]
Fixed in pull request #249
