### ISSUE TITLE
Q: How is the file Forms.min.css generated from Forms.css? 

### ISSUE THREAD

**Issue by tditiecher** [HTBox/crisischeckin#251]
The file Forms.min.css is included in _Layout.cshtml but I don't see any bundles defined for minification of the css (and js). How is this file generated from Forms.css?

(I discovered this while working on issue #26 and had to copy the new class from Forms.css to Forms.min.css by hand. That should not be the way to do it, right?)

**Comment by BillWagner** [comment]
At this time, we should be using the ASP.net mvc bundler for the Cs's files.  

(In the future, I would imagine that we might do that using grunt task on ASP.net vNext. I don't think this is the right time to leap to that framework though.)
