### ISSUE TITLE
Q: How should the check-in functionality work?

### ISSUE THREAD

**Issue by tditiecher** [HTBox/crisischeckin#258]
As the Commitment table has a PersonIsCheckedIn column I assumed that a volunteer first has to create a commitment (register for the disaster for given start and end date). And then when he/she arrives on site he checks-in using the application to his previously created commitment to mark himself as being 'ready for action' (available). As soon as he leaves the site, he checks out (not available). 

Is this the way check-in should work?

In the web application I don't see check-in functionality. Is this only for the mobile native apps? How about adding the check-in / check-out functionality to the volunteer home page.

If the user logs in and has a commitment for the current date we could show an alert/panel on the top of the page with a check-in button:

![image](https://cloud.githubusercontent.com/assets/518175/6398814/8bc8edc6-bdee-11e4-94af-2c0fd9f43b6b.png)

When the user is checked in, this alert will change to an alert/panel with a check-out button:

![image](https://cloud.githubusercontent.com/assets/518175/6398910/4c803eb6-bdef-11e4-9e44-4c61f441da23.png)

**Comment by BillWagner** [comment]
This would be great to add. We do need one or two more states to handle common conditions when traveling to or working at a disaster site. I wrote this page on the wiki to describe the workflows: https://github.com/HTBox/crisischeckin/wiki/Checkin---Checkout-Workflow

**Comment by tditiecher** [comment]
I will implement this feature assuming the following business rules:
* Only a checked-in person can mark himself as unavailable.
* An unavailable person can clear his unavailable state.
* An unavailable person can checkout directly (thereby clearing his unavailable state automatically). 
* An unavailable person will still receive messages only for checked-in volunteers.
* Only a checked-out person can mark himself as delayed.
* A delayed person can clear his delayed state (and still be checked-out).
* A delayed person can check-in directly on arrival.  **Question: do you want to keep the delayed state for historical/reporting purposes?**

The most simple way to implement this is by adding two boolean columns/properties to the Commitments table/object to store the Delayed and Unavailable states. Or does someone have a good reason to implement this by introducing a State enum instead?

**Comment by BillWagner** [comment]
All of those business rules are correct. 
I don't see any reason to keep the delayed status. That's only so that the coordinate knows not to assign immediate tasks to that volunteer.

**Comment by tditiecher** [comment]
I overlooked the already existing [CommitmentStatus enum](https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/Models/Commitment.cs#L21-29). I will add a Delayed status instead of adding new boolean columns as mentioned in my previous comment.

**Comment by tditiecher** [comment]
The checkin/checkout functionality as described here might solve issue #81 although in that issue there's some discussion about GPS and maps.

**Comment by BillWagner** [comment]
@tditiecher I believe you are correct. I'd like @tonysurma to comment as well.

**Comment by tditiecher** [comment]
@BillWagner While implementing functionality for this issue I found out that in the [api/EntitiesController](https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/crisicheckinweb/Api/EntitiesController.cs) some basic check-in/check-out and volunteer functionality is implemented directly in the controller. But in the rest of the application this type of functionality is implemented in the Services assembly. What is the status of this EnititiesController, is this a spike? Shouldn't this controller use the Services layer?

**Comment by BillWagner** [comment]
That was a spike, and it should go through the services layer. Do you want to handle that change?

**Comment by tditiecher** [comment]
@BillWagner While implementing the check-in/check-out on the volunteer home page I thought that it might be a good idea to remove the cluster coordinator (and active) column from the commitments grid as I think this is only relevant information for the current commitment. 
What do you think of this idea (the layout still needs some attention but you'll get the idea)?
![screenshot](https://cloud.githubusercontent.com/assets/518175/6771674/87124570-d0e5-11e4-927b-269f80376ec9.png)

**Comment by tditiecher** [comment]
>> While implementing functionality for this issue I found out that in the api/EntitiesController some basic check-in/check-out and volunteer functionality is implemented directly in the controller. But in the rest of the application this type of functionality is implemented in the Services assembly. What is the status of this EnititiesController, is this a spike? Shouldn't this controller use the Services layer?

> That was a spike, and it should go through the services layer. Do you want to handle that change?

I created a separate issue for this ( #282 ).

**Comment by brunck** [comment]
I suggest we move the WebAPI discussion to that issue (#209).

**Comment by BillWagner** [comment]
@tditiecher I like those suggestions.  Please implement them and send a PR.

**Comment by tditiecher** [comment]
working on it...

**Comment by tditiecher** [comment]
PR #283 implements basic check-in/check-out now.

**Comment by BillWagner** [comment]
I'd recommend we close this, and open a new issue for the statuses of delayed and unavailable. @tditiecher would you agree, or do you want to add that implementation on this issue?

**Comment by tditiecher** [comment]
@BillWagner It's okay to close this issue and create more specific issues for delay and unavailable. I'll not be able to work on it the next week as I have no developer machine at the moment.
