### ISSUE TITLE
Dropdown list when assigning a cluster coordinator contains all persons (unfiltered).

### ISSUE THREAD

**Issue by tditiecher** [HTBox/crisischeckin#259]
First you navigate from the Distaster List to the Cluster Coordinator page for a specific disaster.
Then you can assign a cluster coordinator for each cluster using two dropdown lists (cluster, people).

The people dropdown list contains all persons. When I select a cluster, I expected to see only the persons with that specific cluster id and having a commitment for the disaster in the list of available people.

Is this behaviour intended or is it a bug or incomplete feature?

If the persons should be filtered by commitment do we have to take into account the dates of the commitment or would it be enough to filter on any commitment for the given disaster?

**Comment by BillWagner** [comment]
First, the cluster coordinator dropdown should only contain those volunteers in that cluster. It is an incomplete feature.

On the second, I will ask. For the moment, let's err on the side of having all volunteers rather than only those on site during a given window.

**Comment by tditiecher** [comment]
@BillWagner What do you prefer?
* all persons having a commitment for that specific disaster (not taking into account the dates or checkin status)
* all persons having a commitment for that disaster **and** person.cluster_id equal to the value of the other cluster dropdownlist

The first option is implemented to most easy as the second needs some clientside javascript filtering or ajax calls or even an extra full postback to filter the persons using the cluster id from the first dropdown.

**Comment by BillWagner** [comment]
I think this one gives us the most flexibility:
•or even all persons with that cluster_id (not taking into account if they made a commitment for specific that disaster)
