### ISSUE TITLE
Add checkin / checkout status for "delayed" and "unavailable"

### ISSUE THREAD

**Issue by BillWagner** [HTBox/crisischeckin#284]
The basis for the checkin and checkout workflow has been implemented, but neither of the above listed statuses have been implemented.

See Issue #258 for more details, along with this wiki page: https://github.com/HTBox/crisischeckin/wiki/Checkin---Checkout-Workflow

**Comment by RyanBetker** [comment]
Was going to take this one, but first need to understand the feature needed. I see the 2 status already in the Enum Models.CommitmentStatus, but that just put on the button to "Check in/out".

Should this status be via a button for a Volunteer, say to the right of the CheckIn/Out button?

To better understand, I logged in as a Volunteer to https://crisischeckin-d.azurewebsites.net/  and it gives an error:
There is already an open DataReader associated with this Command which must be closed first.
I thought that error was resolved already? See https://github.com/HTBox/crisischeckin/issues/330

**Comment by BillWagner** [comment]
@RyanBetker Yes, we fixed one version of it. It still seems to be there. Do you want to diagnose that one?  I found one instance where we were using two different services that results in two data readers. There may be others as well.

**Comment by RyanBetker** [comment]
Sure - if I get to it on Sunday would it be ok for that?
See https://github.com/HTBox/crisischeckin/issues/426

**Comment by tonysurma** [comment]
@RyanBetker the rough workflow is that when you are checked in but haven't yet checked out you can indicate that you are either delayed (and therefore not coming at the date you planned (so associated with a different start date) or unavailable (which effective ends your checkin like a checkout but we want to note the unavialble status so we see who said they were coming but then became unavailable.

So like this:
start at 'nothing'  You can checkin with a date range (you are now 'checked in'), you can then do three things
'delayed': also specify a new start date and you are back to 'checked in' from a processing point of view but we want to track when folks are delayed.
'unavailable': closes out your checkin and notes you were unavailable and never checked out.  You are 'done' now.
'checkout': closes out your checkin and notes you checked out.  You are 'done' now.

Hope this somewhat clarifies the workflow :)

**Comment by rwherrmann** [comment]
@rwherrmann is working on this
