### ISSUE TITLE
Writing emails locally is adding new lines

### ISSUE THREAD

**Issue by BanksySan** [HTBox/crisischeckin#296]
Might be linked to #295.  (encoding issue)

Emails written locally are having new lines inserted, breaking links.

e.g.:

    <p>Click on the following link to activate your account: <a href=3D=
    'http://localhost:2077/Account/ConfirmAccount?token=3D1Yn-eeq1WOZ=
    P4W0cUKauew2'>http://localhost:2077/Account/ConfirmAccount?token=3D=
    1Yn-eeq1WOZP4W0cUKauew2</a></p>

**Comment by TravCav** [comment]
@BillWagner just like #295 this is only an issue if you're looking at the html with a text editor. Works fine if opened with email client that reads html formatted emails.

**Comment by BillWagner** [comment]
Closed per @TravCav investigation.
