### ISSUE TITLE
Link & Visible text do not match.

### ISSUE THREAD

**Issue by BanksySan** [HTBox/crisischeckin#297]
Maybe related to #295.

The link text and the visible text do not match:

Text: `http://localhost:2077/Account/ConfirmAccount?token=3D=O9Hu08UVFwN_RvZt1AGUJQ2`
Link:  `http://localhost:2077/Account/ConfirmAccount?token=3DO9Hu08UVFwN=_RvZt1AGUJQ2`

**Comment by RyanBetker** [comment]
Hi - was going to take this one and see about switching the encoding like you'd mentioned might work, but in trying to REPRO on the staging site, it doesn't appear to be a problem. I did notice a missing "s" in successful on the verification page though.

MIME-Version: 1.0
From: "CrisisCheckin Staging" <no-reply@crisischeckin.com>
Date: 26 Aug 2015 21:46:18 +0000
Subject: [STAGING] CrisisCheckin - Activate your account
Content-Type: text/html; charset=us-ascii
Content-Transfer-Encoding: quoted-printable
Message-ID: <px5NPzLWTT-VMrGGl51cRQ@ismtpd0001p1iad1.sendgrid.net>
X-SG-EID: kTzRKEokq2uTTRw+1e3ShzlJbJtHMKaOrFEf08WTk64JyBRYJ9ZM+YFwi/wFiZoneUlcyAfq5L2xBy
 Mkru3irsQXAEhN9q9kDY8r5fNW/5eSNPy46uABiF09Po7w35nJksUaNkwEbjtELHF5n1PZESjhI9Ss
 q2bzp1lfILPE8F1Ddwsegy9nF3hNa3bUtzfQ
X-SendGrid-Contentd-ID: {"test_id":"1440625581"}
X-OriginalArrivalTime: 26 Aug 2015 21:47:39.0904 (UTC) FILETIME=[D45F8000:01D0E048]

<p>Click on the following link to activate your account: <a href=3D'https:/=
/crisischeckin-d.azurewebsites.net/Account/ConfirmAccount?token=3DEe6NUBme6=
c0o8vjBPrqfYQ2'>https://crisischeckin-d.azurewebsites.net/Account/ConfirmAc=
count?token=3DEe6NUBme6c0o8vjBPrqfYQ2</a></p>

Produces: "Account activation was succesful"

**Comment by BillWagner** [comment]
@BanksySan  I think both this and #295 can be closed. Can you verify?

**Comment by BillWagner** [comment]
Closing both this and #295 based on conversation in that issue.
