### ISSUE TITLE
Improvements to CreateMessageToVolunteersByDisaster

### ISSUE THREAD

**Issue by dustycelia** [HTBox/crisischeckin#299]
I see a couple improvements on this page.

1. Change the cluster dropdown to a MultiSelectList.  There will be times where the coordinator will want to contact a couple different clusters, but not all.  For an example, maybe they need to send an email to coordinate the Food Cluster and Protection cluster.  The people giving out food need protected (very bad mockup attached).

![image](https://cloud.githubusercontent.com/assets/9878642/8277980/2b882252-188d-11e5-9f25-773c5b08bb84.png)

2. Send button is annoying as is placed on the left of the screen.  Takes me a full second or two to get over there to the left.  It would be better placed to the right of the email form.  This is more natural feeling and closer to where the mouse probably already is (very bad mockup attached).

![image](https://cloud.githubusercontent.com/assets/9878642/8278100/8ddf3354-188e-11e5-92f2-b40502d67b94.png)

**Comment by BillWagner** [comment]
@dustycelia Your second suggesting is great: Please move the Send button. On this first, I'd like @tonysurma to weigh in. My understanding is that the cluster coordinators are interacting only with their own cluster. I want to make sure that any features we add map to the org's current workflow. (At least until we have some live feedback.

**Comment by lodieric** [comment]
I'll give this one a shot.
