### ISSUE TITLE
Register: unable to register due to problem with SMTP settings

### ISSUE THREAD

**Issue by kinetiq** [HTBox/crisischeckin#300]
I'm in the very early stages of getting involved, and the first thing I did was connect to the staging server and attempt to create a new user. That failed with the message: 

The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.5.1 Authentication Required.

Here is the relevant part of the stack trace: 

[SmtpException: The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.5.1 Authentication Required. Learn more at]
   System.Net.Mail.MailCommand.CheckResponse(SmtpStatusCode statusCode, String response) +1525339
   System.Net.Mail.MailCommand.Send(SmtpConnection conn, Byte[] command, MailAddress from, Boolean allowUnicode) +46
   System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, Boolean allowUnicode, SmtpFailedRecipientException& exception) +88
   System.Net.Mail.SmtpClient.Send(MailMessage message) +1852
   Services.SmtpMessageSender.SendMessage(Message message, IReadOnlyCollection`1 recipients, String senderDisplayName) +236
   Services.MessageCoordinator.SendMessage(Message message, List`1 recipients, String senderDisplayName) +107
   Services.MessageService.SendMessage(Message message, Person recipient, String senderDisplayName) +109
   crisicheckinweb.Controllers.AccountController.Register(RegisterModel model) +432

...My apologies if this is a known issue or if there's a more appropriate way to communicate this. I did search the open issues before posting. I learned that email is intentionally disabled in staging, but I suspect an exception that blocks registration is probably not what you intended. :)

**Comment by BillWagner** [comment]
This problem and the proposed work is covered in issue #286. The comments have the proposed solution detailed. I'd like to continue the conversation there. 
@kinetiq Would you like to dive in on the code portion? @BanksySan was also looking, but I don't know if he's had time to devote to it in the last couple weeks.

**Comment by BanksySan** [comment]
@BillWagner @kinetiq Haven't had a chance to do anything for a couple of weeks.
