### ISSUE TITLE
SMS messages can be sent instead of email

### ISSUE THREAD

**Issue by BillWagner** [HTBox/crisischeckin#303]
In many situations, email is not easy to deliver, but SMS messages will reach the recipients. (Think recovery zones).

We need a way for a user to configure any message that can be sent via email to be sent via SMS. 

If you want this issue, message one of the coordinators. We have arrangements with Twilio to use there service for this feature.

**Comment by BillWagner** [comment]
Note that if an SMS message is chosen, the app should limit the length of the message.

**Comment by jsucupira** [comment]
I can work on this enhancement.
