### ISSUE TITLE
Wrong http response code received when user accesses resource without session

### ISSUE THREAD

**Issue by htbox-tester** [HTBox/crisischeckin#31]
Scenario, log in and visit http://crisischeckin.azurewebsites.net/Home/Assign.  Logout and revisit http://crisischeckin.azurewebsites.net/Home/Assign directly.  Will receive 404 resource not found.  Should respond with appropriate HTTP status code or redirect to login page.

**Comment by tditiecher** [comment]
It seems that this issue cannot be reproduced: 
* The Home/Assign page doesn't exist (anymore?).
* When trying to replay this scenario with other pages, the user is correctly redirected to the login page.

**Comment by BillWagner** [comment]
@tditiecher You are correct. This got fixed in some of the security work around the mobile interfaces. However, the issue was not referenced.
