### ISSUE TITLE
ViewVolunteer filter is receiving internal server error 500.

### ISSUE THREAD

**Issue by cgollubske** [HTBox/crisischeckin#326]
The view volunteer page is showing no information due an internal server error.

POST http://localhost:2077/Volunteer/Filter 500 (Internal Server Error)

**Comment by BillWagner** [comment]
Verified with @mgollubske that this is a bug in the razor view. It's only in the feature branch being used for the cluster taxonomy changes.

**Comment by BillWagner** [comment]
fixed in #327
