### ISSUE TITLE
Blank activity causes SQL insert error

### ISSUE THREAD

**Issue by bobofett86** [HTBox/crisischeckin#333]
If the activity portion for Volunteer for Disaster is left blank (No selection options available) Hitting volunteer returns an error page "The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Commitment_dbo.Cluster_ClusterId". The conflict occurred in database "crisischeckin-dev", table "dbo.Cluster", column 'Id'.
The statement has been terminated."

**Comment by TravCav** [comment]
This scenario should not happen any more.  Disasters require at least one cluster and when volunteering the user can't not select a cluster.  *activities are clusters now*

**Comment by BillWagner** [comment]
Verified on 11/20.
