### ISSUE TITLE
Need a confirm email field on registration

### ISSUE THREAD

**Issue by bobofett86** [HTBox/crisischeckin#335]
Easy to mistype email addresses, should have a verify email address field like many major websites that require signup.

**Comment by jsucupira** [comment]
I can look into this.

**Comment by jsucupira** [comment]
What is the minimum browser requirement for this website?
Can I rely on html 5 validation?

**Comment by tonysurma** [comment]
Html5 validation should be fine and we will want to perform the validation on server as well so that gives us a fall back.
________________________________

**Comment by jsucupira** [comment]
I decided not to go with html 5 validation, because I believe jquery.validate.js was interfering with it.
