### ISSUE TITLE
System allows same cluster name to be created.

### ISSUE THREAD

**Issue by alexfdietz** [HTBox/crisischeckin#345]
Nothing special in the repro path.  As admin user enter a new cluster name same as one that already exists.  Screen shows 3 entries of cluster "aaa".  

This was found as part of the StarWest virtual conference.  

![image](https://cloud.githubusercontent.com/assets/14914703/10207679/8a6aefde-6793-11e5-8cfc-fb065d329b33.png)

**Comment by jsucupira** [comment]
I can work on this one.
