### ISSUE TITLE
Cluster name >= 50 characters throws exception.

### ISSUE THREAD

**Issue by alexfdietz** [HTBox/crisischeckin#350]
49 characters long is OK.  50 characters errors out.  Screen shot below.

This was found as part of the StarWest virtual conference.  

![image](https://cloud.githubusercontent.com/assets/14914703/10208334/5205bb4c-6798-11e5-8fe3-737448c9119a.png)

**Comment by alexfdietz** [comment]
There's also some strange behavior with the web browser forward/backward buttons.  If I go "back" one page from the error above, I can enter a string 50 characters long and it'll take.

**Comment by jsucupira** [comment]
I can work on this one.
