### ISSUE TITLE
Grammar error on date range error message.  Placement could be better

### ISSUE THREAD

**Issue by alexfdietz** [HTBox/crisischeckin#364]
yeah yeah yeah, those damn testers and their grammar bugs.  Sure but details count, especially to be a world class application. See the screen shot.

Also - I suggest moving the error message location closer to the actual date range fields.  After entering dates & location, the user's focus is on the "volunteer" button,  not where the error messsage shows up. It would be more fluid to put the system's error response in the vicinity of the date ranges.

bug found during starwest virtual conference. 

![image](https://cloud.githubusercontent.com/assets/14914703/10224144/3cc42856-6822-11e5-8029-958362a5346a.png)

**Comment by mqg** [comment]
Fixed the grammar mistake in PR#419 ("a end date" -> "an end date"), but did not move the error message.

**Comment by BillWagner** [comment]
Fixed in PR #419
