### ISSUE TITLE
When logged in as user I see no option to "schedule a trip"

### ISSUE THREAD

**Issue by htbox-tester** [HTBox/crisischeckin#38]
Requirement #3 for users seems to indicate the user should be able to schedule a new trip.  I see no such a option for trip unless that is a requirement defect unless that is supposed to say "disaster".

**Comment by tditiecher** [comment]
What has to be done before this issue can be closed?

**Comment by BillWagner** [comment]
This should be closed as the vocabulary on the requirements has changed.
