### ISSUE TITLE
User is able to send a message without selecting a Cluster

### ISSUE THREAD

**Issue by mchan948** [HTBox/crisischeckin#383]
1) Login as Admin
2) Click button for "Add New Disaster"
3) Enter "Bad Disaster" in the Name field
4) Click Create button
5) Click link for Send Message to Volunteers
6) Enter "test" in the Message field
7) Click Send button

Expected Result: User should be prompted to select at least one Cluster
Actual Result: Message is sent

**Comment by BillWagner** [comment]
Fixed in PR #422
