### ISSUE TITLE
Activity field should be disabled when a value has not been selected for  Volunteer for Disaster field

### ISSUE THREAD

**Issue by mchan948** [HTBox/crisischeckin#388]
1) Create an account
2) Login as the newly created account
3) Expand Activity drop down

Expected Result: Activity field should be disabled since a value for Volunteer for Disaster has not been selected and this field is what drives the values for Activity
Actual Result: It kind of expands but not all the way since there are no values (looks weird)

**Comment by mjmilan** [comment]
Can one of the project contributors please review this to see if it is still an issue? 

![htbox](https://cloud.githubusercontent.com/assets/6794223/14280691/293e4f62-fb2c-11e5-88a3-3c049a9c6634.png)

Whilst I agree it's not consistent when compared to the other control's with their "choose one" defaults, I don't think this looks all that strange.

Do we continue with this issue, or can we close it?

**Comment by BillWagner** [comment]
@tonysurma Can you give this a look?

**Comment by tonysurma** [comment]
I'm okay with this as is
