### ISSUE TITLE
Long value in Activity drop down extends past the field itself

### ISSUE THREAD

**Issue by mchan948** [HTBox/crisischeckin#390]
1) Create an account
2) Login as the newly created account
3) Select Enron in the Volunteer for Disaster drop down
4) Expand Activity field

Expected Result: Values are displayed properly
Actual Result: The value "&&&&&&&&&&&&&&&&&&&&" extends past the Activity field (looks terrible)

**Comment by TravCav** [comment]
tested in IE, chrome, and firefox. Didn't see it extend past field.  looks okay.

**Comment by BillWagner** [comment]
Also verified. Closing.
