### ISSUE TITLE
Any New Phone Number is accepted when changing a user's contact info

### ISSUE THREAD

**Issue by mchan948** [HTBox/crisischeckin#392]
1) Create an account
2) Login as the newly created account
3) Click on link for Change Contact Info
4) Enter "11" for New Phone Number field

Expected Result: Validation error message thrown specifying that this is not a legitimate phone number
Actual Result: Information saved successfully

**Comment by TravCav** [comment]
Not sure we should limit the input on this.  What are the requirements for "legitimate" phone number?  Depending on the environment that's been setup 11 may be a valid extension.

**Comment by TravCav** [comment]
duplicate of #293

**Comment by BillWagner** [comment]
Closing as duplicate of #293
