### ISSUE TITLE
Volunteer for Disaster field label should be simplified to just Disaster

### ISSUE THREAD

**Issue by mchan948** [HTBox/crisischeckin#394]
1) Create an account
2) Login as the newly created account

Expected Result: 1st field should just be labeled as Disaster as the user is selecting from a list of disasters
Actual Result: 1st field is labeled as Volunteer for Disaster.

**Comment by TravCav** [comment]
This can be closed. It got fixed in PR #418.

**Comment by BillWagner** [comment]
Closed per PR #418
