### ISSUE TITLE
In the Commitment for today section, messages being displayed should not be using button labels as part of the message itself

### ISSUE THREAD

**Issue by mchan948** [HTBox/crisischeckin#397]
1) Create an account
2) Login as the newly created account
3) Select "Fake Cluster 1" in the Volunteer for Disaster field
4) Select "On Site" for Location field
5) Click Volunteer button

Expected Result: In the Commitment for today section, messages displayed should not be using labels of a button as part of the message itself.
Actual Result: In the Commitment for today section, there is a message displayed saying," and start helping now!" after the Check-in button.  Messages displayed should not be using labels of a button as part of the message itself.

**Comment by mjmilan** [comment]
Subject to my Pull Request being accepted, I believe this issue can be closed.

**Comment by BillWagner** [comment]
fixed in #489
