### ISSUE TITLE
In the Commitment for today section, there should be separators between the fields names and values selected

### ISSUE THREAD

**Issue by mchan948** [HTBox/crisischeckin#398]
1) Create an account
2) Login as the newly created account
3) Select "Fake Cluster 1" in the Volunteer for Disaster field
4) Select "On Site" for Location field
5) Click Volunteer button

Expected Result: In the Commitment for today section, there should be a separator between the field names and values selected for readability purposes (ex. Disaster: Fake Cluster 1)
Actual Result: There are no separators

**Comment by wadewachs** [comment]
mchan948 - are you at the conference, or playing along from home? If you are here at the conference, please stop by and let me know who you are.

**Comment by wadewachs** [comment]
@mchan948 I believe you are participating via the virtual conference. If that is not the case, please let me know in the next 20 minutes, by 4:00 pm PDT today.

Thanks for all your work on reporting bugs today. Great work!

**Comment by rwherrmann** [comment]
@BillWagner I think this one may already be complete.

**Comment by BillWagner** [comment]
@rwherrmann Thanks for verifying. It should have been closed with PR #423, but I missed tagging it.

closing now.
