### ISSUE TITLE
Special Characters along with Alpha and Numeric

### ISSUE THREAD

**Issue by justinstilwell** [HTBox/crisischeckin#400]
login to page
create new crisis
Copy and Paste
"a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!"

giving a Server Error in '/' Application. issue

**Comment by TravCav** [comment]
went to /Disaster/Create
Entered a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!a1!

page returned errors
•The field Disaster name must be a string with a maximum length of 50.
•Disaster name cannot have special characters.

**Comment by ryan-mcguire** [comment]
I'm working on this.

**Comment by TravCav** [comment]
@ryan-mcguire can you confirm that it's working okay now? I think it got fixed since the original issue was put in.

**Comment by ryan-mcguire** [comment]
You're correct... this is indeed fixed.

**Comment by BillWagner** [comment]
Closing per above converstation
