### ISSUE TITLE
Deleting cluster

### ISSUE THREAD

**Issue by justinstilwell** [HTBox/crisischeckin#401]
Delete from the page go back, delete is still in existence then error appears.

login to page
go to cluster page
delete cluster
hit back button
cluster reappears
delete
error thrown

Server Error in '/' Application.

The DELETE statement conflicted with the REFERENCE constraint "FK_dbo.Commitment_dbo.Cluster_ClusterId". The conflict occurred in database "crisischeckin-dev", table "dbo.Commitment", column 'ClusterId'.
The statement has been terminated.

**Comment by ryan-mcguire** [comment]
I'm looking into this one.
