### ISSUE TITLE
Multi Browsers - Deleting clusters while having messages send with clusters selected

### ISSUE THREAD

**Issue by justinstilwell** [HTBox/crisischeckin#403]
Login to Crisis Checkin
Open another tab
immediately opens with current session log ins
select send message to volunteers
select both clusters to send messages to
in other browswer delete the cluster
hit send

system exception handle error.

**Comment by mtherien** [comment]
I'll take a look at this

**Comment by mtherien** [comment]
I tried to reproduce this and cannot.  I'll dig into the code to see if there is something I am missing in reproducing

**Comment by mtherien** [comment]
It appears the code never looks at the clusters selected so it never filters the recipient list.  I'm not sure how this failed before.

@BillWagner @tonysurma This should be closed.  Created issue #458 to track the problem of not filtering the list.

**Comment by johnmwright** [comment]
Is this still an issue that needs to be fixed?
