### ISSUE TITLE
Creating a new cluster with a cluster name more than 50 character throws an exception

### ISSUE THREAD

**Issue by awesomeqa** [HTBox/crisischeckin#409]
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Comment by jsucupira** [comment]
Isn't this the same issue as #350?

**Comment by TravCav** [comment]
Confirmed. Same as #350.  This was fixed in your pull request #356

**Comment by BillWagner** [comment]
Closed. Fixed in PR #356
