### ISSUE TITLE
Create button is twoards the bottom on Add new disaster page

### ISSUE THREAD

**Issue by Ashwiniajay** [HTBox/crisischeckin#413]
Its confusing as there is a big list of disaster in between New disaster name and create button

**Comment by TravCav** [comment]
Those are clusters that will be added to the disaster upon creation.  The layout could look prettier but the page seems fine how it is.  I would close this issue. 

Created #432 to address the confusing nature of the cluster section on that page.

**Comment by BillWagner** [comment]
Agree. Closed, and moving conversation on updates to #432
