### ISSUE TITLE
The send message to volunteers text box is allowing text to be entered.

### ISSUE THREAD

**Issue by shipra3183** [HTBox/crisischeckin#415]
the text box has a limit of characters but still it allows to enter the text message and is not restricting the user.
As a user, the user should be restricted and not allowed to enter to avoid any confusion as users do not ideaaly count how many characters have been entered.

**Comment by TravCav** [comment]
The limit only applies if "Send Message via SMS" is checked.  If checked there's a message with a character count that , if the count is greater than 160 characters, turns red and submission fails.  This seems to work as designed.  We could consider stopping any characters being entered after the 160 limit if the SMS option is checked as  a feature.  Current functionality seems fine.

**Comment by BillWagner** [comment]
Verified and closed.
