### ISSUE TITLE
System presents volunteer change contact info page instead of volunteer home page, at user login. 

### ISSUE THREAD

**Issue by alexfdietz** [HTBox/crisischeckin#416]
I found a use case in which a volunteer login goes to a different page than the volunteer home page.  It is related to managing the state of the browser.

1. logged into as a new user called "starwest"
2.  on volunteer home page, click on change contact info. 
3. on change info page, click on Logout starwest
4. on the login page, click the browser's back button

The system presents the login page, but the url is for the change contact page.
5.enter login information (as in step 1)

System does not present volunteer home page; directly to change info page.

**Comment by wadewachs** [comment]
@alexfdietz - You are one of our winners from the Virtual Test Lab! Thanks for all your submissions and testing on this product.

Send me an email with your address so I can ship your prize to you.

wadewachs (at) gmail (dot) com

Congratulations!

**Comment by rwherrmann** [comment]
@rwherrmann is going to work on this issue.

**Comment by rwherrmann** [comment]
@rwherrmann will work on this one.
