### ISSUE TITLE
When I first run the application on my machine, I get an exception logging in as the test user.

### ISSUE THREAD

**Issue by pottereric** [HTBox/crisischeckin#429]
I cloned the repo to my local machine. I tried to log in with the test user credentials ("TestUser", "test"). I was navigated to the crisicheckinweb\Views\Home\Index.cshtml page, but I got a null reference exception. 

The error comes from the following line:

<td>@comm.Cluster.Name</td>

**Comment by TravCav** [comment]
Bob and TestUser didn't get a cluster in their commitment assignment in DbConfig.SeedIfNotEmpty.   Very sad for bob and testuser.  
You can't make a commitment without selecting a cluster through the front end so not sure if that field needs to be made not nullable or if the system should be able to accept commitments to disasters without an cluster/activity.

**Comment by BillWagner** [comment]
Fixed in PR #430
