### ISSUE TITLE
Updating cluster without changing anything throws an error

### ISSUE THREAD

**Issue by TravCav** [HTBox/crisischeckin#431]
Updating cluster without changing anything throws ClusterAlreadyExistsException();.  Does anyone have any preference on how they'd like that to fail more gracefully?  Can we just have it ignore the action and continue on like nothing happened instead of failing?

**Comment by BillWagner** [comment]
Ignore the action, and continue would be great. I'd be even happier if the response had a status that said something to the effect of "the requested cluster already exists"

**Comment by BillWagner** [comment]
Fixed in PR #433
