### ISSUE TITLE
Create / Edit Disaster page needs laid out better

### ISSUE THREAD

**Issue by TravCav** [HTBox/crisischeckin#432]
The cluster section on the disaster create/edit page is a little confusing for first time users creating a new disaster. 
Needs to be made a little clearer what it's doing. Also creating a new cluster from there does not lead back to the disaster create/edit page.  Would probably be okay if the create new cluster just wasn't on that page since it's not specific to that disaster anyway.

**Comment by BillWagner** [comment]
Can you add a comment on what you would like it to look like? Let's review it before you invest a lot of time.

**Comment by TravCav** [comment]
Break up the form to better distinguish between disaster fields and cluster fields.  Maybe set the cluster section off to the right. And put a note saying at least one must be selected.

"Add new cluster" button just takes the user to the add new cluster page but doesn't return to the disaster being edited.  This takes the user out of the workflow they were in.  I see the disaster Id gets put in the url.  Maybe we can just put a textbox at the bottom of the cluster table on the disaster edit page and add it from there with some ajax so we don't even leave the page.

I think it was mentioned in another issue to add a select/deselect all.

**Comment by BillWagner** [comment]
@TravCav Those are all good ideas. I'd be happy to see a pull request for this.
