### ISSUE TITLE
Missing step in GetStarted documentation

### ISSUE THREAD

**Issue by mdoleh** [HTBox/crisischeckin#443]
In the setup document (https://github.com/HTBox/crisischeckin/blob/master/Contributing.md) there is a step missing where the database needs to be created manually in solution explorer first under the App_Data folder before trying to run the Database update command.

**Comment by mjmilan** [comment]
Are we sure this is the case? I have just deleted my connection in visual studio 2015, then deleted the files from the AppData folder using Windows Explorer, and then used 

`update-database -projectName Models`

This seems to have worked fine, created and seeded the database for me...

**Comment by mdoleh** [comment]
Forgot to mention, this is on Visual Studio 2013.

**Comment by mjmilan** [comment]
Does it not regenerate the database in response to update-database? I would not have expected this to be dependent on the version of studio used... 

Can you recreate the issue?

**Comment by mdoleh** [comment]
Honestly, I don't remember exactly what the issue was. I believe it would throw an error instead of generating the database when running the command. I ran through the setup as part of a conference session and was instructed to open this issue by @tonysurma after finding that creating the database manually then running the command was the fix.

**Comment by mjmilan** [comment]
Ok... I don't have access to a VS2013 installation here, but I could try it out from the office in the morning...

**Comment by mjmilan** [comment]
Just ran a quick test - the project no longer compiles under VIsual Studio 2013 because someone has made use of the safe navigation operator (?.).

**Comment by BillWagner** [comment]
Ugh. I missed that in review. @mjmilan since you found it, if you get me a PR I will merge it right away.

**Comment by mjmilan** [comment]
Hi Bill,

I'm working on the day job at the mo... Can you wait until tonight (8 or 9 hours) for the PR?

Martin

**Comment by BillWagner** [comment]
:+1:

**Comment by mjmilan** [comment]
PR #488 BIll - just had a coffee break and it's not a big job.

**Comment by mjmilan** [comment]
@tonysurma I think this can be closed.

**Comment by tonysurma** [comment]
yep, thx again
