### ISSUE TITLE
Send email to volunteers does not consider filter by selected cluster

### ISSUE THREAD

**Issue by mtherien** [HTBox/crisischeckin#458]
Discovered when looking at #403 .

The code never filters recipients based on the selected clusters.  MessageService.SendMessageToDisasterVolunteers needs to consider cluster ids passed.

**Comment by mtherien** [comment]
I'll start on this since I'm here

**Comment by mjmilan** [comment]
Can this be closed now given we have a code contribution on it? Did it work?

**Comment by BillWagner** [comment]
Yes, it can be closed. It looks like the PR didn't use the magic 'fixes' syntax, and I missed it when I merged the PR. Closing now.
