### ISSUE TITLE
Need captcha on register

### ISSUE THREAD

**Issue by drosskopf** [HTBox/crisischeckin#46]
Currently there is noting stoping you from having a billion users generated from a computer,  need captcha to stop robots

**Comment by tditiecher** [comment]
How about sending a confirmation token to the registered email address (similar to the password reset mail with link)? We could then use the [WebSecurity.ConfirmAccount](https://msdn.microsoft.com/en-us/library/gg569286(v=vs.111).aspx) method to activate the user.

**Comment by BillWagner** [comment]
@tditiecher I like that solution better than captcha. Please put that together.

**Comment by tditiecher** [comment]
@BillWagner What do you want?
* should I prevent the user from logging in as long as he doesn't click on link in the activation mail or
* should the user be able to login but without any role and thus unable to volunteer or perform other actions?

Personally I think the first option is the most clear (as long as we provide an error message that activation is required) but it's your call ;-)

**Comment by BillWagner** [comment]
I agree that the first option is the best.
