### ISSUE TITLE
Modify Volunteer Registration to include Organizations

### ISSUE THREAD

**Issue by NaveenP94** [HTBox/crisischeckin#471]
In order to incorporate Organizations in user profiles we will need to slightly modify the volunteer registration page to allow for an person to select from a drop down which organization they would like to affiliate with. The data for this drop down can be pulled from the Organization profiles #470

The default should be "Independent" *note this will not be an entry in the Organization table

**Comment by mjmilan** [comment]
I believe @tonysurma has already done this. 

Can we close this one Tony?
