### ISSUE TITLE
Update Volunteer Home Page to Display Associated Organization Name

### ISSUE THREAD

**Issue by NaveenP94** [HTBox/crisischeckin#474]
Since we are adding Organizations into the system, the Organization name that the profile is associated with should be displayed on the Volunteer Home page in the same area as "Commitment for today" the association for this will be added in issue #469

**Comment by mjmilan** [comment]
@tonysurma Can this issue not be closed now?

**Comment by tonysurma** [comment]
Yes, wasn't auto updated from the PR
