### ISSUE TITLE
Change Resource Checkins table name

### ISSUE THREAD

**Issue by NaveenP94** [HTBox/crisischeckin#492]
For the Silver Dragon exercise we are repurposing the resources table to handle reporting of tasks completed and hazards.

- [x]  So if we could change the name of the table on the "View Checkins" page to "Field Reported Data" that would be great. 

- [x] On the "Volunteer Home" page if we could change the title "Checkin a New Organization Resource" to "Report New Data"

**Comment by mjmilan** [comment]
Pull request #496 completes both of the tasks for this issue.
