### ISSUE TITLE
Active session shows login page when you go to Administrator only page

### ISSUE THREAD

**Issue by htbox-tester** [HTBox/crisischeckin#50]
Steps to reproduce:
1.Login with normal account
2.Go to http://crisischeckin.azurewebsites.net/Disaster/List
3.Log In is displayed

**Comment by tditiecher** [comment]
@gmoshe27 Are you still planning to fix this issue?

**Comment by gmoshe27** [comment]
@tditiecher So sorry for the lat reply. I haven't thought about this in over a year. Would you like me to take it on, or are you looking to do it yourself / close the issue?

**Comment by tditiecher** [comment]
I can have a look, just wanted to make sure not to step on your toes...

**Comment by gmoshe27** [comment]
go for it! I can lend some help if you need it.
