### ISSUE TITLE
Task/Request table Details

### ISSUE THREAD

**Issue by NaveenP94** [HTBox/crisischeckin#501]
We would like to create a task/request table, this is basically where the EOC main decision makers can put out tasks to the volunteer community and people can assign themselves to them. We should have it such that only the Admin account can submit tasks. The fields for the columns of this table should include

- Entry Made (this is a time stamp of when it was submitted)
- Description (open text field)
- Organization (this will be who submitted the request, for right now this will just be the administrator, but later on we need to create different permission levels for different types of accounts)
- Type ( this will be a standardized "type" of request)
- End Date (when the task must be completed by)
- Location (open text field admin can put the address or GPS coordinates)
- Assign (we want to create a button here to allow a volunteer to assign a task to them selves)**

**This button should be similar in function to the "Add as Contact" button currently on the view checkins page. On the same page as this request table at the bottom we should have a table showing the volunteers tasks assigned to them, similarly how when you click "Add as Contact" the connection shows up at the bottom of the page under "Organization Contact". This list should just have the task description, due date, and a button called "complete". When the button is clicked it should disappear from this list, and be marked complete from the admin view. 

For the admin view instead of a "Assign" column we should have a "Status" field so that when an admin goes to the task/request table they can see either "unassigned", "assigned to _____" or "completed by _____"  next to tasks.

**Comment by andrewhart098** [comment]
I am working on this

**Comment by andrewhart098** [comment]
For now, I am going to assume a one to one relationship between Request and Volunteer. In other words, only one volunteer can be assigned (or assign themselves) to a request.

**Comment by andrewhart098** [comment]
I believe this issue can be closed now that #643 has been merged.

**Comment by BillWagner** [comment]
Thanks @andrewhart098 Closing now.

FYI: If you put "fixes #501" (substitute the correct issue number) in the PR description, GitHub will close the issue when the PR is merged.
