### ISSUE TITLE
Create separate page for Field reported data

### ISSUE THREAD

**Issue by NaveenP94** [HTBox/crisischeckin#502]
Currently we have all the checkins and contact information as well as connections on the same page as the field reported data. It might be easier to move the Field reported data to another page and another tab on the red ribbon next to "View Checkins" called "View Data", once the tab is clicked it should take the user to a page that is the same as the page when "View Checkins" is clicked, so the title can be "List Data" and choose a disaster and filter by date.

**Comment by andrewhart098** [comment]
This feature has been taking care of with pull request #639 and can be closed.

cc @tonysurma

**Comment by tonysurma** [comment]
Thanks!
