### ISSUE TITLE
Enhancement: Not able to edit profile

### ISSUE THREAD

**Issue by drosskopf** [HTBox/crisischeckin#52]
If I change my name, email or phone, there is no way to update my profile information.

**Comment by tditiecher** [comment]
It is already possible to change your email and phone via Change Contact Info but you cannot change your first and last name.
Should I read this issue as "Add editable fields for first and last name to the Change Contact Info form." or does it mean something else or can this issue be closed?

**Comment by drosskopf** [comment]
This issue can probably be closed

**Comment by BillWagner** [comment]
Yes, this has been added and merged at CodeMash.
