### ISSUE TITLE
Ability to view checkins, phone numbers of other volunteers. 

### ISSUE THREAD

**Issue by aarjay** [HTBox/crisischeckin#530]
https://crisischeckin-d.azurewebsites.net/Volunteer/ListbyDisaster

![screenshot 2016-05-04 at 4 47 35 pm](https://cloud.githubusercontent.com/assets/5223163/15028669/f9871ae4-1217-11e6-803e-0fd37a79fffc.png)

@jbtestpilot - Jon Bach

**Comment by NaveenP94** [comment]
What is the issue here?

**Comment by aarjay** [comment]
Jon Bach when testing using his own login, observed that he could view contact information of "Other" checked-in users. And found it to be an issue with data compromise.
