### ISSUE TITLE
virtual Add commitment form : end and start date unknown Form

### ISSUE THREAD

**Issue by nesrinezouari** [HTBox/crisischeckin#538]
#virtual  
1- add start date or End Date in Add commitment form 

Expected result : date form DD/MM/YYYY
Obtained result : Date form MM/DD/YYYY
![date form](https://cloud.githubusercontent.com/assets/5974675/15031202/e1be0efe-124e-11e6-89b0-4c947b9be2f5.JPG)

**Comment by NaveenP94** [comment]
Unclear what is the issue here? The date format that we are using is MM/DD/YYYY

**Comment by tonysurma** [comment]
Thanks for the testing issue. As Naveen stated we are currently only support MM/DD/YYYY
