### ISSUE TITLE
On the List of Volunteers page, there is only one date control on the date filter.

### ISSUE THREAD

**Issue by htbox-tester** [HTBox/crisischeckin#57]
This is more of a question than a bug; but on the List of Volunteers page, the user can only pick a single date to generate a list of volunteers for a Disaster. Would it be more useful to be able to pick a range of dates and generate a list of volunteers for a period of more than a single day.

**Comment by tditiecher** [comment]
What is the status of this issue, are the requirements more clear now?

**Comment by BillWagner** [comment]
I will close this.  The core use case is to reach volunteers that are currently checked in.

Later, we will need to reach folks enroute, or delayed. I'll add new tasks and feature descriptions what that will entail.
