### ISSUE TITLE
Volunteer Home Page

### ISSUE THREAD

**Issue by tabithavj** [HTBox/crisischeckin#583]
The "checkins" should be spelled "check-ins" to maintain continuity

**Comment by tabithavj** [comment]
The "checkin/check-out" buttons should be a bit clearer

**Comment by tabithavj** [comment]
Should the "view checkins" display checkins, or commitments?

**Comment by tabithavj** [comment]
The "Make New Commitment", "Report New Data" doesn't seem to allow new fields to be entered, only pre-existed

**Comment by tabithavj** [comment]
REmoved disaster, "Not Another Disater," but it remained in the dropdown for "Make a New Commitment" and "Report New Data"

**Comment by mjmilan** [comment]
Why have you closed this?
