### ISSUE TITLE
Invalid user email brings up unfriendly error screen

### ISSUE THREAD

**Issue by julielebo** [HTBox/crisischeckin#599]
If a user edits their email and does not enter a valid email, such as lebo.julie.gmail (no @) and saves the contact info, then an error screen appears that says "Value cannot be null". It should do some validation on the entry and warn the user before saving.

![screenshot 2016-05-05 at 2 59 12 pm](https://cloud.githubusercontent.com/assets/8533315/15053740/f97d09a4-12d1-11e6-872b-d8b3413b7632.png)

**Comment by cmgutmanis** [comment]
Working on this
