### ISSUE TITLE
"View CheckIns" link doesn't work prior to logging in

### ISSUE THREAD

**Issue by miketull** [HTBox/crisischeckin#606]
P1, virtual

Before logging in, when the mobile view button is clicked, the “View CheckIns” link appears, but doesn’t work.  It should either work or not display until after the user has logged in.

**Comment by andrewhart098** [comment]
The button should probably not appear before logging in.  I have created pull request #640 to address this issue.

**Comment by andrewhart098** [comment]
The pull request has been accepted and this issue can now be closed.
