### ISSUE TITLE
Phone numbers aren't validated

### ISSUE THREAD

**Issue by miketull** [HTBox/crisischeckin#608]
P2, virtual

On “Create new account” page https://crisischeckin-d.azurewebsites.net/Account/Register, no validation of phone number format.  Was able to enter 41755512123 and 417!555!1212.

I realize that if the application is to be used internationally, then phone number validation becomes complex.  Perhaps it should at least validate for acceptable characters.

**Comment by lhanscom** [comment]
See PR #636

**Comment by BillWagner** [comment]
Fixed in PR #636
