### ISSUE TITLE
Admin: View Volunteers: List don't populate

### ISSUE THREAD

**Issue by drosskopf** [HTBox/crisischeckin#63]
I select a disaster, with our without a filter date, and I cannot get any individuals to show up on the list.  
![crisis2](https://f.cloud.github.com/assets/5590134/1256230/4dd1ee54-2b92-11e3-890b-38f911a85f84.png)

**Comment by tditiecher** [comment]
@BillWagner As wadewachs says, the page does function. Is there anything to be done before this issue can be closed?

**Comment by BillWagner** [comment]
I would agree that this is ready to close.
