### ISSUE TITLE
Error on login page - FIX REQUIRED

### ISSUE THREAD

**Issue by NaveenP94** [HTBox/crisischeckin#641]
There seems to be a small bug that may have occurred due to maybe a file not being committed properly or a path was specified incorrectly. The error is probably in the Views folder and has to do with one (or more) layout files. 

follow this link to see the error message:
https://crisischeckin-d.azurewebsites.net/Account/Login?ReturnUrl=%2f

![bug](https://cloud.githubusercontent.com/assets/17274028/15931854/61faa232-2e27-11e6-9744-475c52fb05cd.PNG)

**Comment by tonysurma** [comment]
I'm looking at this, it appears to be in the build... maybe didn't make it into project file or into the build on the website...

**Comment by tonysurma** [comment]
Fixed this via PR #642
