### ISSUE TITLE
Contributing using Visual Studio 2015

### ISSUE THREAD

**Issue by ktngoykalolo** [HTBox/crisischeckin#647]
Would like to know if there are any particular changes to the way we contribute using VS 2015 ? 
Is there any plans to move to .NET Core/ ASP.NET Core?

**Comment by tonysurma** [comment]
There are no issues contributing using VS2015 that I am aware of (it is what I and many others have been using) so you should be good.

As for .NET Core/ASP.NET Core, we have another project http://github.com/htbox/allready that is on asp.net core now and likely we will move this one to core 'someday' but for now am focused on building on top of the current stack for the foreseeable future.

Thanks for your interest and hope to help you contribute to a project!
