### ISSUE TITLE
Web App - Volunteer - Error when navigating to My Organization

### ISSUE THREAD

**Issue by gmford** [HTBox/crisischeckin#683]
When I log in as TestUser and navigate to My Organization, a server error is generated. 

![myorgerror](https://cloud.githubusercontent.com/assets/20876231/17457888/2ade6998-5bca-11e6-8ae2-9b02fc1d6893.png)

**Comment by TheTopher** [comment]
Hey, I'll take this.

**Comment by tonysurma** [comment]
I am going to break this out into 2 issues.  This one and a separate one to check and see if you can register/create a user a without an organization per @cmgutmanis finding.

**Comment by cmgutmanis** [comment]
@tonysurma yup you're right. You can create a new user with no organization, though you can really only (afaik) create a new organization as a volunteer so there could be a situation with a new instance of the app where there's no orgs and no users to create them

**Comment by tonysurma** [comment]
I just made a new issue that captures that and @TheTopher 's changes now make sure there is always an org seeded in the database at start so we should be able to break that cycle

**Comment by johnmwright** [comment]
@tonysurma it looks like you committed a fix against this issue. Is there still more work to be done or should this issue be closed?

**Comment by tonysurma** [comment]
thanks for finding that @johnmwright and welcome to the project!
