### ISSUE TITLE
Web App - Volunteer - On the Volunteer Home page, I cannot save data

### ISSUE THREAD

**Issue by gmford** [HTBox/crisischeckin#694]
I complete fields in the 'Report New Data' section and click 'Checkin':
![reportnewdata](https://cloud.githubusercontent.com/assets/20876231/17459079/cf73da12-5bf0-11e6-9948-108514deec4f.png)

But my data doesn't appear after the page refreshes:
![reportnewdatamissing](https://cloud.githubusercontent.com/assets/20876231/17459081/d51736a8-5bf0-11e6-92f6-67c3713b4b5b.png)

**Comment by TheTopher** [comment]
I was watching the video that Tony provided earlier today that demonstrated this page.  I noticed that the behavior in the video is as you outline above (and I found it rather jarring watching it).  To see your data you have to go to another page.  Is this by design?

**Comment by tonysurma** [comment]
This is not by design, it should show the data on the current page.  I think it is a refresh or UI issue as, as you said, the data is saved it just isn't displayed.
