### ISSUE TITLE
Editing the disaster name with html tags in the textbox throws an exception

### ISSUE THREAD

**Issue by htbox-tester** [HTBox/crisischeckin#71]
Here is the exception when I tried to add html tags:

[HttpRequestValidationException (0x80004005): A potentially dangerous Request.Form value was detected from the client (Name="<html> Out of Lemon ...").]
   System.Web.HttpRequest.ValidateString(String value, String collectionKey, RequestValidationSource requestCollection) +9667213
   System.Web.<>c__DisplayClass5.<ValidateHttpValueCollection>b__3(String key, String value) +18
   System.Web.HttpValueCollection.EnsureKeyValidated(String key) +9666613
   System.Web.HttpValueCollection.GetValues(String name) +17
   System.Web.Mvc.ValueProviderResultPlaceholder.GetResultFromCollection(String key, NameValueCollection collection, CultureInfo culture) +20
   System.Web.Mvc.<>c__DisplayClass8.<.ctor>b__4() +19
   System.Lazy`1.CreateValue() +416
   System.Lazy`1.LazyInitValue() +10785795
   System.Lazy`1.get_Value() +75
   System.Web.Mvc.NameValueCollectionValueProvider.GetValue(String key, Boolean skipValidation) +63
   System.Web.Mvc.ValueProviderCollection.GetValueFromProvider(IValueProvider provider, String key, Boolean skipValidation) +55
   System.Web.Mvc.<>c__DisplayClass9.<GetValue>b__4(IValueProvider provider) +34
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +145
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +171
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source) +164
   System.Web.Mvc.ValueProviderCollection.GetValue(String key, Boolean skipValidation) +251
   System.Web.Mvc.DefaultModelBinder.BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext) +314
   System.Web.Mvc.DefaultModelBinder.GetPropertyValue(ControllerContext controllerContext, ModelBindingContext bindingContext, PropertyDescriptor propertyDescriptor, IModelBinder propertyBinder) +17
   System.Web.Mvc.DefaultModelBinder.BindProperty(ControllerContext controllerContext, ModelBindingContext bindingContext, PropertyDescriptor propertyDescriptor) +367
   System.Web.Mvc.DefaultModelBinder.BindProperties(ControllerContext controllerContext, ModelBindingContext bindingContext) +89
   System.Web.Mvc.DefaultModelBinder.BindComplexElementalModel(ControllerContext controllerContext, ModelBindingContext bindingContext, Object model) +55
   System.Web.Mvc.DefaultModelBinder.BindComplexModel(ControllerContext controllerContext, ModelBindingContext bindingContext) +1171
   System.Web.Mvc.DefaultModelBinder.BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext) +380
   System.Web.Mvc.ControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor) +296
   System.Web.Mvc.ControllerActionInvoker.GetParameterValues(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +105
   System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__1e(AsyncCallback asyncCallback, Object asyncState) +445
   System.Web.Mvc.Async.WrappedAsyncResult`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +129
   System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state) +302
   System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__17(AsyncCallback asyncCallback, Object asyncState) +30
   System.Web.Mvc.Async.WrappedAsyncResult`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +129
   System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state) +338
   System.Web.Mvc.Async.WrappedAsyncResult`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +129
   System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +316
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +15
   System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__2(AsyncCallback asyncCallback, Object asyncState) +71
   System.Web.Mvc.Async.WrappedAsyncResult`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +129
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +251
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) +48
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +16
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +301
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
 

--------------------------------------------------------------------------------

**Comment by BanksySan** [comment]
Why is this a bug?  The first thing I did on the site was try to XSS it.

If we need to be able to format documents, maybe we should be looking at Markdown instead of HTML?

**Comment by BillWagner** [comment]
We should not support HTML, but we should handle the attempted XSS attacks with more grace than an exception and a yellow screen of death.

**Comment by BanksySan** [comment]
@BillWagner  I agree with that, a yellow screen can be confusing for a user trying to legitimately format  a document.

What use cases are there?  There are a few off-the-shelf solutions.  Github's own one being a very good contender.

**Comment by BillWagner** [comment]
@BanksySan We can safely limit it to ASCII text. If there is an off the shelf markdown that would be good, that would be fine too.

**Comment by RyanBetker** [comment]
@BillWagner, Has anyone else started a Resource file in another fork? If so, please point out the source location so I can bring that over and match the structure, otherwise I will plan to add the default english Resources.resx to the Common proj.

Feel free to assign this to me bug. I've researched this a bit and we could put a simple Regex attribute on the ViewModel.  Planned code: [RegularExpression("^[A-Za-z0-9,.]*$")]//, ErrorMessageResourceName = DisasterNameIsInvalid)] //in resx: DisasterNameInvalidDisasterNameIsInvalid = "Disaster name cannot have special characters.")]

Also, related bug - when clicking the Update button and you have an invalid name (to update a name or the assigned clusters, it bombs with IndexOutOfRangeException). Reason being is the page submits to /Create and there's an ActionLink trying to get the 3rd section of the url (id), which isn't there.
I started an idea with toggling the action name to Edit if there's a Model.ID, but that action source is Deprecated.

What helps to get around this is it needs an IF check before the usage of the url
@if (Request.Url.Segments.Length > 2)

**Comment by BillWagner** [comment]
@RyanBetker No one is actively working on this issue. Please add the English resource as a good starting point. 

Thank you.

**Comment by RyanBetker** [comment]
Did a search in the sln for Resources, and found this following namespace, so I used it and have formatted the keyname the same pattern. Resources.DefaultErrorMessages.InvalidDisasterName.


Will be working on getting my fork reverted before putting in a pull request.
My fork still has Auth0 starter (read: experimentation) in it, and I don't want to have those in the pull request. Made a separate repo for updates, but can't start a Pull Request with the way it's linked.

**Comment by RyanBetker** [comment]
Who would be available to help me with some git roadblocks?
Tried ample things to get my fork reset. Not there just yet.

These first 2 did not result in the fork having the original code of HTBox/master
http://stackoverflow.com/questions/1683531/how-to-import-existing-git-repository-into-another/
http://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream
http://scribu.net/blog/resetting-your-github-fork.html (no permission for this)

**Comment by RyanBetker** [comment]
@BillWagner , would you please recommend someone to help out on the source control issue with Git and resetting my fork? Please let me know either way. If no one is available, I will delete the fork, but I'd prefer not to do so and understand how to reset the Fork for my own learning.

I have the bug fix all done and ready to do a pull request, it's just that the fork needs to be reset as I don't want to be pushing up the Auth0 starter, as it is not useful to the project.

**Comment by jsucupira** [comment]
There two link explains how to do it.  I did it this weekend and it worked fine.
https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/

**Comment by BillWagner** [comment]
@jsucupira Thanks for the quick reply. I was traveling, and not able to get online yesterday.

**Comment by RyanBetker** [comment]
thank you. I've looked over those docs and I'm not finding resources in them to help with *resetting a fork to an upstream*. (my fork is already made and it's a bit cluttered with the Auth0 stuff I want to back out)Is there something I'm missing in it?

**Comment by jsucupira** [comment]
See screenshot below with step by step on how to do it.

![image](https://cloud.githubusercontent.com/assets/1004621/9831588/08c18bb6-592c-11e5-9ce9-bff4443cebac.png)

**Comment by RyanBetker** [comment]
@jsucupira, I really appreciate the lessons in git here. I hope it's not too trivial for you; I'm happy to learn. I come from a long VSS and TFS background myself.

Looking at my fork online as well, it appears all reset now. Tomorrow I will see about cherry picking the bug fixes/changes that exist on another branch, but have a busy schedule, so it will be a few days.

**Comment by jsucupira** [comment]
No problem, I am new on git as well.  My background is also on TFS.

**Comment by RyanBetker** [comment]
All should be ready for review and merge.

I created a pull request here - https://github.com/HTBox/crisischeckin/pull/331
and tagged Bill Wagner on that.
