### ISSUE TITLE
Potential Issue support older versions of IE

### ISSUE THREAD

**Issue by htbox-tester** [HTBox/crisischeckin#72]
The site should support older version of IE including IE7 and IE8 that come with Windows XP.   We noticed during test-a-thon that numerous users received an ASP server error when accessing various features from within the site using IE8.

**Comment by tditiecher** [comment]
@BillWagner Is this issue still relevant (the html/javascript has changed a lot in the last 1.5 years and the error 'accessing various features' is very unclear)?

**Comment by BillWagner** [comment]
I'll bump to @tonysurma but I believe this can be closed.

**Comment by BillWagner** [comment]
This can be closed. We will not support that down-level of browser.
