### ISSUE TITLE
No validation of the volunteer phone number data entry

### ISSUE THREAD

**Issue by giamyers** [HTBox/crisischeckin#73]
When registering as a Volunteer, I entered a random alphabetic character string ("dkfnpwoigfapoif") for phone number (no hyphens or special characters) and the system accepted it.  Should have checked that the filed was numeric.
Then I clicked the back button, and entered the following numeric string:  dkfnpwoigfapoif
I clicked "Create New Account" button and the system gave an error:  The provided anti-forgery token was meant for user "", but the current user is "Janey". 
FYI, Janey is what I entered for the username.

**Comment by tditiecher** [comment]
The error is the same as in issue #33 . Possibly a duplicate.

**Comment by BillWagner** [comment]
Yes, I will close as a duplicate. Of #33 and #51
