### ISSUE TITLE
My Commitments table has not edit/delete option

### ISSUE THREAD

**Issue by giamyers** [HTBox/crisischeckin#75]
If I change my mind as a user, and I want to modify or delete one or more rows of the My Commitments table, I have no ability to do that.  Should add a modify button and delete button.

**Comment by tditiecher** [comment]
What is the status of this issue? it's been quiet for over a year now. I can look into this.

**Comment by BillWagner** [comment]
I believe it's still open. I never did get a pull request that addressed it. I'd be happy to have @tditiecher take this on.

**Comment by tditiecher** [comment]
Ok, I'll have a look at it.

**Comment by tditiecher** [comment]
It seems this feature is already implemented in commit https://github.com/HTBox/crisischeckin/commit/f9692cab (13 feb 2014).

I can volunteer for a disaster and remove it again from the list (using the remove button in the last column of the grid on the Volunteer Home page).

This issue can be closed, or?

**Comment by tditiecher** [comment]
@BillWagner This issue can be closed, or?

**Comment by BillWagner** [comment]
Yes, this can be closed. Thanks for finding the correct pull request.
