### ISSUE TITLE
The same user account is accessible, if the broswer is closed and re-opened without logging out.

### ISSUE THREAD

**Issue by doggietrot** [HTBox/crisischeckin#87]
Found in IE9.  This may present a security issue. If said browser is not configured to clear cookies each time the user closes the browser, for example, like on a banking website, then the same account re-open upon re-visiting the same page. 

Steps:

1.Go to the volunteer website
2.Log in as a user.
3.Close the browser.
4.Re-open the browser.

**Comment by asherw** [comment]
User will be logged out when the session expires.
Not many browsers are setup to clear cookies when they're closed.
I think you'll find that majority of sites where you login, will also act the same way.

Banking websites are a different kettle of fish.  I don't believe the same rules should apply here.

I would recommend that this item should be closed.

**Comment by BillWagner** [comment]
@asherw I would agree.
