### ISSUE TITLE
Volunteer Home - Volunteer for Disaster - Disaster Names are not unique

### ISSUE THREAD

**Issue by htbox-tester** [HTBox/crisischeckin#91]
Multiple disasters exist with the same name.  These should be unique.

**Comment by evclay** [comment]
I am curious.  I noticed @BillWagner  said this was starting to be implemented.  Did it ever get completed?

**Comment by BillWagner** [comment]
@evclay This has been implemented. See here for the code: https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/Services/DisasterService.cs#L74

The added tests are here: https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/Services.UnitTest/DisasterServiceTest.cs#L352

and here: https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/Services.UnitTest/DisasterServiceTest.cs#L471

It looks like I did not close this issue at that time. Fixing now.
